import 'package:freezed_annotation/freezed_annotation.dart';

import 'package:i12_into_012/models/todo.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'app_state.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'app_state.g.dart';

@freezed
///Verwalten den Status der App
abstract class AppState with _$AppState {
  ///Erstellt ein Appsatet Objekt
  const factory AppState({
    required List<Todo> todos,
    required bool isDarkMode,
    required bool asksForDeletionConfirmation,
    required Set<String> selectedTodoIds,
  }) = _AppState;

  factory AppState.initial() => const AppState(
        todos: [],
        isDarkMode: false,
        asksForDeletionConfirmation: true,
        selectedTodoIds: {},
      );

  factory AppState.fromJson(Map<String, dynamic> json) =>
      _$AppStateFromJson(json);
}
